eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 10000
spring:
  application:
    name: eureka-server
server:
  port: 8761